spring:
  profiles:
    active: local

server:
  port: 8081
topics:
  retry: library-events.RETRY
  dlt: library-events.DLT
---

spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic: library-events
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    # only for tests
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    admin:
      properties:
        bootstrap-servers: localhost:9092, localhost:9093, localhost:9094

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
  # localhost:8081/h2-console; sa user